name: ci

on:
  push:
    # branches:
    #   - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          version = cat Dockerfile | grep 'wg_go_tag=' | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'

          TAG=$version make build
          # TAG=$version make push

          TAG=latest make build
          # TAG=latest make push
